// um bom lugar para guardar provider!!
// abrigada todas as aplicações

import { DM_Sans } from 'next/font/google'
import { DefaultProviders } from '@/components/default-providers'

const dmSans = DM_Sans({ 
  weight: ['300', '400', '500', '600'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <DefaultProviders>
          {children}
        </DefaultProviders>
      </body>
    </html>
  )
}
